CHARACTER = [
    "9-year-old",
    "Terminally ill adult", 
    "Mother of five",
    "Politician up for re-election",
    "Professional dog walker",
    "Retired boxer",
    "Newly arrived immigrant",
    "Nun",
    "Grocery store cashier",
    "Disgraced movie star",
    "Eccentric billionaire",
    "Frustrated writer",
    "Art museum intern",
    "Teenage prodigy",
    "Ex-con sous chef",
    "Rabbi questioning their faith",
    "Olympic silver medalist",
    "Gambling-addicted principal",
    "Burned out archaeologist",
    "Soldier suffering from PTSD",
    "12-year-old hacker",
]


SITUATION = [
    "Makes a breakthrough scientific discovery",
    "Witnesses a mob hit",
    "Has a sibling who marries their worst enemy",
    "Struggles to direct a community theater production",
    "Must accompany an aging parent across the country",
    "is stranded by car failure",
    "Falls in love with a psychopath",
    "is a lone survivor of mass tragedy",
    "is Cut off from family inheritance",
    "is Desperate for social media followers",
    "Goes on their first vacation ever",
    "is Arrested for a crime they didn’t commit",
    "is Chosen to appear on their favorite gameshow",
    "Fakes their own death",
    "Gets lost on a hiking trip",
    "Discovers a long-lost sibling",
    "is Seduced into joining a cult",
    "Has one week to find a particular person",
    "is Kidnapped on a safari",
    "Wakes up with no memories"
]

